### PR TITLE
Try to fix macos unit tests

### PR DESCRIPTION
**Pull request by oleks-rip**
## High Level Overview of Change
MACOS unit tests fix

### Context of Change

Add retries to Env RPC requests to fix Macos disconnects during CI testing.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### API Impact

- [x] No API impact

### CODE REVIEW

**Comment by oleks-rip** [comment]
Attempt1 
max retries observed
```
ripple.app.ValidatorRPC
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
ERR:Env Env::do_rpc error, retrying...
```

**Comment by ximinez** [comment]
This is a duplicate of #5171

**Comment by oleks-rip** [comment]
> This is a duplicate of #5171
Ohh, didn't saw that one.

UPDATE:
@ximinez  Don't you find #5171 more heavier  than it need to be?

**Comment by ximinez** [comment]
> UPDATE: @ximinez Don't you find #5171 more heavier than it need to be?

It seems that way, but I ran into several edge cases and one-offs that made most of those changes necessary. Particularly to get the parallel tests working.

**Pull request closed without merging**
