### PR TITLE
Add the`fixEmptyDID` amendment

### PR DESCRIPTION
**Pull request by mvadari**
## High Level Overview of Change

This PR introduces an amendment that fixes a problem where DIDs can be empty, which shouldn't be able to happen. An empty DID object is equivalent to not having a DID object at all, so there is no need to take up the extra object reserve.

### Context of Change

If a`DIDSet` transaction is sent with one or two of the fields (`DIDDocument`/`Data`/`URI`) as an empty string, when there is no pre-existing DID, the `DID` object is created with empty fields.

Recreation: https://devnet.xrpl.org/transactions/A73FEA27EF6A24438A7E9A3B8192B1C0B430E503A14212933CAFF54C66C51FCD

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Performance (increase or change in throughput and/or latency)
- [x] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

## Test Plan

A unit test was added that reproduces the issue. The test ensures that behavior remains the same pre-amendment, and is the desired behavior post-amendment.

### CODE REVIEW

**Comment by seelabs** [comment]
This needs a better commit message. When opening a PR I'd like it to have the proposed commit message and that commit message should be part of the review (plus a good commit message helps the reviewers as well).

Many people do this (I'm sure I do this myself), but I'd like us to get out of the habit of doing.

**Review by seelabs — APPROVED** [review]
:+1: LGTM

**Review by gregtatcam — APPROVED** [review]
👍 LGTM

**Comment by mvadari** [comment]
Proposed commit message:
```
`fixEmptyDID`: ensure that empty DIDs cannot be created (#4950)

This amendment fixes an edge case where an empty DID object can be
created. It adds an additional check to ensure that DIDs are
non-empty when created, and throws a `tecEMPTY_DID` error if the DID
would be empty.
```

**Comment by mvadari** [comment]
@seelabs @ximinez this is ready to merge.

**Pull request merged**
