### PR TITLE
Switch to self-hosted runners for macOS

### PR DESCRIPTION
**Pull request by thejohnfreeman**

### CODE REVIEW

**Review by shichengripple001 — APPROVED** [review]
look good to me

**Review by legleux — APPROVED** [review]

**Review by scottschurr — APPROVED** [review]
LGTM.  Thanks for doing his.

Just for grins I pushed this branch to my personal GitHub.  It tried to run MacOS tests.  For over 30 minutes the display showed this:
```
Requested labels: self-hosted, macOS
Job defined at: scottschurr/rippled/.github/workflows/macos.yml@refs/heads/john-macos
Waiting for a runner to pick up this job...
```
After that I canceled the workflow.  I'm assuming that's expected behavior.  The self-hosted runners will only pickup from develop or some such.

Not complaining.  Just making sure that's expected behavior.

**Comment by ckniffen** [comment]
> It's expected behavior if you have not yet added a self-hosted runner to your personal fork. See these [instructions](https://github.com/ripple/github-runner#macos-runner) for Ripple employees. If you create a PR, the workflow will be picked up by the self-hosted runners attached to the upstream project. XRPLF/rippled already has some, as does my fork.

Those instructions are not visible for me.  Those should probably be documented elsewhere.

**Comment by intelliot** [comment]
I can view the instructions, but I guess they are private to certain users; I don't have permission to modify the repo's visibility. @shichengripple001 owns the repo. @shichengripple001, can you grant Read access to members of the Ripple github org?

Alternatively: Is there any reason why the repo can't be made open source?

**Pull request merged**
