### PR TITLE
clang warning about deprecated sprintf usage

### PR DESCRIPTION
**Pull request by ckeshava**
## High Level Overview of Change

This fix is intended to remove a warning from the clang compiler. It switches the usage of sprintf function into the recommended snprintf function.

I observed this issue in this environment:
```
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Fix https://github.com/XRPLF/rippled/issues/4569

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by ckeshava** [comment]
@intelliot @a-noni-mousse @seelabs 
I have grabbed the relevant suggestions from the old [PR](https://github.com/XRPLF/rippled/pull/4570) into this pull request.

**Review by HowardHinnant — APPROVED** [review]
Looks good!

**Review by Bronek — APPROVED** [review]
LGTM

**Review by scottschurr — APPROVED** [review]
:+1: Change looks good.  The changed line is also exercised by the unit tests, which increases my confidence..

**Comment by intelliot** [comment]
- removes a warning. Perf attention not needed. cc @sophiax851

**Pull request merged**
