### PR TITLE
Add hubs.xrpkuwait.com to bootstrap

### PR DESCRIPTION
**Pull request by alloynetworks**
@Xrpkuwait is a committed contributor to XRPL infrastructure. His hubs will provide a much needed extra set of bootstrap servers. They have shown good uptime and capacity.

### CODE REVIEW

**Comment by Xrpkuwait** [comment]
Thank you.

I confirm my commitment to operate the **hubs.xrpkuwait.com** servers for a minimum of 2 years.
**XRPKuwait.com** is an XRPL infrastructure provider based in Kuwait, operating 7 nodes, including public hubs and a validator.

**Review by ximinez — CHANGES_REQUESTED** [review]
Please also update the default list of servers in the example config https://github.com/XRPLF/rippled/blob/develop/cfg/rippled-example.cfg#L417-L419

**Comment by ximinez** [comment]
> > Please also update the default list of servers in the example config https://github.com/XRPLF/rippled/blob/develop/cfg/rippled-example.cfg#L417-L419
> 
> Added via #5167

Sorry, my intention was that both changes would be included in this PR. It's one change that should be merged together, specifically using the "Squash and merge" button to put the changes into a single commit.

**Comment by alloynetworks** [comment]
Combined with 5167 in 5169

**Pull request closed without merging**
