### PR TITLE
Fix output of remote step in nix workflow

### PR DESCRIPTION
**Pull request by ckeshava**
## High Level Overview of Change
This pull request updates the nix CI runner. Although the builds are successful, the binaries are not uploaded to the internal artifactory. This PR attempts to fix this issue and I have borrowed the idea from @ximinez

After successful authentication, outcome variable contains a string. In the upload step, we are checking if outcome == success as a prerequisite for uploading the binary.

This PR updates the contents of the outcome variable in the CI.

Example of a breaking Github Actions workflow (thanks to @thejohnfreeman): https://github.com/XRPLF/rippled/actions/runs/6264131645/job/17010134246

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release
- [x] None of the above
This does not modify any of the source code files. 

This change as motivated from this slack discussion: https://ripple-enterprise.slack.com/archives/C02GE9NBA/p1695051230548129

### CODE REVIEW

**Comment by ckeshava** [comment]
This pull request supercedes https://github.com/XRPLF/rippled/pull/4716

@ximinez @thejohnfreeman I have collected all the changes into this PR

**Review by ximinez — APPROVED** [review]

**Comment by ximinez** [comment]
It is very rarely necessary to close a PR and open a new one for the same change set, even if there are fixes. For something small like this, it's not a big deal, but for something larger, I'd have to start over completely, and that's a big pain in the neck.

**Comment by ckeshava** [comment]
@ximinez My apologies, I understand the inconvenience. I'll keep that in mind for the next time.

**Comment by ximinez** [comment]
> @ximinez My apologies, I understand the inconvenience. I'll keep that in mind for the next time.

No worries. I realized after I wrote the comment that this was the one you _couldn't_ push to anymore, which completely justifies making a copy. In this case. :grin: (Which is why I deleted the comment, too.)

**Review by thejohnfreeman — APPROVED** [review]

**Comment by intelliot** [comment]
@ckeshava - from your perspective, please confirm if this PR is ready to merge

**Pull request merged**
