### PR TITLE
Create CLion-Cmake-Settings.md

### PR DESCRIPTION
**Pull request by ckeshava**
This file describes trouble shooting steps for configuring CLion IDE

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [x] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by ckeshava** [comment]
@intelliot  @thejohnfreeman  @mtrippled  Let me know if this document accurately captures your thoughts. I'm hoping it will help onboard new contributors with CLion IDE

**Comment by ckeshava** [comment]
Okay, yeah that sounds good.
Regards,
Keshava

**Comment by nbougalis** [comment]
Thank you for doing this, @ckeshava!!! I haven't been able to load the project in CLion since the migration to Conan.

While the compilation not working in-IDE isn't a big deal, the inability to load resulted in a ton of secondary, subtle breakage (e.g. navigation) that aggravated me to no end.

Even if people don't think this is appropriate in-repo I would suggest putting it as a wiki article on here and if that isn't accepted, consider putting this up as a blog post on your personal blog.

**Comment by intelliot** [comment]
Personally, I think one could find a home for this [on xrpl.org](https://github.com/XRPLF/xrpl-dev-portal/pulls)

**Comment by ckeshava** [comment]
It's so great to hear from you Nik! Yes, I was pulling my hair by the time
I got this to work on CLion :P
Once we are used to the features of an IDE, it's so hard to live without
them.

@Elliot Lee ***@***.***>  Yes, I spoke to Rome Reginelli about this,
I hope it can be accommodated on some kind of trouble-shooting wiki.
Regards,
Keshava

**Review by thejohnfreeman — CHANGES_REQUESTED** [review]
I mildly object to putting IDE instructions into this project, but I've objected to other documents that I feel are out-of-scope and been outvoted every time.

I think if this document is added to the project, it should see these changes first:

- Put this document under `docs`, alongside the platform-specific instructions in `environment.md`. We should minimize the number of entries in the root directory.
- Rename the file to not use uppercase letters. This matches the existing style in `docs` and avoids any future issues around case sensitivity on filesystems.
- Rewrite any use of the first-person "I".
- [Rewrite](https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/) all "click here" links.
- Add blank lines after headings and around lists and images.
- Fix missing punctuation and capitalization.

**Comment by intelliot** [comment]
@ckeshava can you put this content in [a wiki page](https://github.com/XRPLF/rippled/wiki)?

**Comment by ckeshava** [comment]
Sure, I can do that.

Regards,
Keshava

**Comment by ckeshava** [comment]
I have included a wiki page here: https://github.com/XRPLF/rippled/wiki/Building-rippled-codebase-with-CLion-IDE

**Pull request closed without merging**
