### PR TITLE
Proposed 2.0.0-rc1

### PR DESCRIPTION
**Pull request by intelliot**
## High-Level Overview of Change

The base branch is `release` because [all releases (including betas)](https://github.com/XRPLF/rippled/blob/develop/CONTRIBUTING.md#before-you-start) go in `release`.

## Context of Change

When finalized, the next stable release of `rippled` is expected to be the last one for 2023. The major version is bumped due to:
- General availability of `api_version` 2 (expected).
  - This [api_version](https://github.com/xrplf/rippled/blob/develop/API-CHANGELOG.md) is not available yet (except in beta, requiring a configuration change), but it will be in the next release.
- New `server_definitions` method.
- Notable performance improvements in TPS (transactions per second).
- XLS-38 sidechains support
  - This is a large change and adds significant new functionality to the protocol.
- XLS-40 DID support
- Lastly, lots of code has been refactored and changed since the [previous](https://github.com/XRPLF/rippled/releases/tag/1.0.0) major version bump.

### Type of Change

- [x] Release

### CODE REVIEW

**Review by manojsdoshi — APPROVED** [review]
LGTM

**Review by ximinez — CHANGES_REQUESTED** [review]
In its current state, this branch has diverged from what has been merged to `develop`, and includes a PR that has since been withdrawn.

**Comment by Bronek** [comment]
> In its current state, this branch has diverged from what has been merged to `develop`, and includes a PR that has since been withdrawn.

Also the PR https://github.com/XRPLF/rippled/pull/4775 which was approved and merged in `develop` , in this branch is missing its last commit

**Comment by intelliot** [comment]
Closing in favor of https://github.com/XRPLF/rippled/pull/4810 (which has already been merged to `release`).

**Pull request closed without merging**
