### PR TITLE
Support for the mold linker

### PR DESCRIPTION
**Pull request by seelabs**
This adds support for the mold linker on linux. On my system this significantly improves link time (from about 18 seconds to about 1 second).

### CODE REVIEW

**Comment by sublimator** [comment]
Siiiick, but awwww, linux only?

**Comment by sublimator** [comment]
https://github.com/bluewhalesystems/sold

Payware, but would be totally worth it

**Review by thejohnfreeman — APPROVED** [review]

**Comment by Bronek** [comment]
I tested this under Ubuntu 22.04 container - in this environment `gold` is always installed because it is included in `binutils` , and `mold` is an extra package, so we can have both, but we cannot have `mold` alone without `gold`. With the last commit "Use first non-default linker" it all works and the link time with `mold` is so fast, I can barely spot it (not kidding!)

**Review by Bronek — APPROVED** [review]
Thanks, it works !

**Pull request merged**
