### PR TITLE
Consistently show ledger_index as integer on JSON output

### PR DESCRIPTION
**Pull request by Bronek**
## High Level Overview of Change

Several methods in API version 1 return `ledger_index` as a quoted number, i.e. string type.  This value should be consistently returned as a number. It was reported in https://github.com/XRPLF/clio/issues/722#issuecomment-1614973809 and I missed it in earlier changes meant for API version 2

### Context of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

### API Impact

- [ ] Public API: New feature (new methods and/or new fields)
- [x] Public API: Breaking change (in general, breaking changes should only impact the next api_version)
- [ ] `libxrpl` change (any change that may affect `libxrpl` or dependents of `libxrpl`)
- [ ] Peer protocol change (must be backward compatible or bump the peer protocol version)

#### Before:
JSON output from `ledger` would contain ledger as string e.g. `"ledger_index": "54300932"` 

#### After
JSON output from `ledger` would contain ledger as number e.g. `"ledger_index": 54300932`

### CODE REVIEW

**Comment by Bronek** [comment]
Reworking this for API version 3 ( _this comment will be deleted when I'm done_ )

**Comment by mvadari** [comment]
This resolves this issue: https://github.com/XRPLF/rippled/issues/3652

**Review by HowardHinnant — APPROVED** [review]

**Review by ximinez — APPROVED** [review]
Looks good. I left one suggestion, but it's not a biggie.

**Comment by intelliot** [comment]
@Bronek please update this PR so the change applies in api_version 2

**Comment by Bronek** [comment]
> @Bronek please update this PR so the change applies in api_version 2

Done. Only change in change description was needed; I switched it to API version 2 last week in https://github.com/XRPLF/rippled/pull/4820/commits/62d51a08a578fbce53575c6607e431c2e6dca87f

**Comment by kennyzlei** [comment]
We have this corresponding issue for Clio to maintain parity https://github.com/XRPLF/clio/issues/1014

@Bronek @intelliot would be appreciated if we can have a rippled issue created with the API Change label in the future so we can catch these breaking API changes quicker for Clio folks to work on that side 🙏

**Pull request merged**
