### PR TITLE
Proposed 2.0.0-b1

### PR DESCRIPTION
**Pull request by intelliot**
## High Level Overview of Change

This is a beta for the next release. This PR's diff shows all of the changes since the last release (1.12.0).

Highlights:
- https://github.com/XRPLF/rippled/pull/4292
- [Several changes](https://github.com/XRPLF/rippled/milestone/6?closed=1) to improve performance

The base branch is `release` because [all releases (including betas)](https://github.com/XRPLF/rippled/blob/develop/CONTRIBUTING.md#before-you-start) go in `release`.

## Context of Change

When finalized, the next stable release of `rippled` is expected to be the last release for 2023 (given the holidays in Nov/Dec). The major version is bumped because:
- `api_version` 2 general availability
  - This [api_version](https://github.com/xrplf/rippled/blob/develop/API-CHANGELOG.md) is not available yet (except in beta, requiring a configuration change), but it will be in the next release.
- Notable performance improvements in TPS (transactions per second).
- XLS-38 sidechains support
  - This is a large change and adds significant new functionality to the protocol.
- Lastly, many aspects of the code have been refactored and changed since the [previous](https://github.com/XRPLF/rippled/releases/tag/1.0.0) major version bump.

Comparison: https://github.com/XRPLF/rippled/compare/1.12.0...develop-next

Note that the replacement for getting and setting thread name (#4312) was reverted, so it is **not** in this release.

### Type of Change

- [x] Release

### CODE REVIEW

**Review by manojsdoshi — APPROVED** [review]
LGTM

**Comment by intelliot** [comment]
Please ignore the accidental close. I just rebased this commit in order to include a couple more PRs:

- #4634
  - This has been waiting for a while.
- #4702
  - This reverts a change which never went into a release. Reverting now prevents churn in the API (i.e. we don't want the API to change in one release, and then revert back in the next release - it's better to keep it stable and only change once, when it's actually ready to go). Furthermore, there are problems on Windows if we don't include this revert.

**Comment by intelliot** [comment]
notes:
- Proposed 2.0.0-b1 (4854508d39) :+1: on linux, macOS
- Fails on Windows; requires #4708 
- #4707 may be needed in order to create targets during packaging

**Comment by intelliot** [comment]
Rebased to add #4708. This is expected to build on Windows now.

**Comment by intelliot** [comment]
- Force pushed to include:
  - #4709 
  - #4707

This is now ready for re-review at 046d0c2f0af89067aea0d245da706a35c5f99046.

**Comment by intelliot** [comment]
@legleux to confirm inclusion of #4707

**Comment by legleux** [comment]
> @legleux to confirm inclusion of #4707

Looks good

**Review by ximinez — APPROVED** [review]

**Review by HowardHinnant — APPROVED** [review]

**Pull request merged**
