### PR TITLE
README - add link to ripple-server mailing list

### PR DESCRIPTION
**Pull request by intelliot**
## High Level Overview of Change

Since April 2013, there has been a Google Group used for release announcements. Server operators should subscribe in order to receive an email when a new version of the rippled server software is released.

### Context of Change

People sometimes ask whether there is an email list and/or a way to be notified of new releases via email.

### Type of Change

- [x ] Documentation Updates

### CODE REVIEW

**Comment by bharathchari** [comment]
I think it's better if we originate mail (mailing list) from the xrpl.org domain. We're working on creating list-manager services that would operate under lists.xrpl.org and have one of them as an announce channel for software-releases.

**Comment by manojsdoshi** [comment]
@intelliot can you please fix the merge conflicts for this PR when you get a chance so we can merge it in, or we can close it and wait for the foundation to submit a PR cc @bharathchari

**Comment by intelliot** [comment]
This is good to merge now, and it can be changed later, whenever XRPLF wants to.

**Comment by intelliot** [comment]
@bharathchari - Agreed - we will update the README again when the xrpl.org mailing list is ready.

**Pull request merged**
