### PR TITLE
Revert 4505 4760 

### PR DESCRIPTION
**Pull request by sophiax851**
### Type of Change

Reverting these PRs until they can be fully tested in a simulated realistic environment with potential network scenarios that may occur on the MainNet.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release
- [x] Require performance testing on a simulated realistic environment to cover potential network scenarios

### API Impact

- [ ] Public API: New feature (new methods and/or new fields)
- [ ] Public API: Breaking change (in general, breaking changes should only impact the next api_version)
- [ ] `libxrpl` change (any change that may affect `libxrpl` or dependents of `libxrpl`)
- [ ] Peer protocol change (must be backward compatible or bump the peer protocol version)

### CODE REVIEW

**Comment by seelabs** [comment]
I'm seeing a compile error:
```
/home/swd/projs/ripple/theirs/src/ripple/rpc/handlers/ServerInfo.cpp: In constructor ‘ripple::detail::ServerDefinitions::ServerDefinitions()’:
/home/swd/projs/ripple/theirs/src/ripple/rpc/handlers/ServerInfo.cpp:290:39: error: ‘FastWriter’ is not a member of ‘Json’
  290 |         const std::string out = Json::FastWriter().write(defs_);
      |                                       ^~~~~~~~~~
```

**Comment by intelliot** [comment]
> This patch should fix the above issue: [seelabs@b79bbfe](https://github.com/seelabs/rippled/commit/b79bbfebd9c378be58be135eea1fbac0d127a085)

Thank you! I pushed your commit to this PR.

**Review by seelabs — APPROVED** [review]
:+1:

**Review by scottschurr — APPROVED** [review]
:+1: with the reverts plus the patch.  I confirmed that...

1. The new code exactly matches machine produced reverts of the two commits in question, and no conflicts were reported in the reverts.
2. The branch builds, both debug and release, on my machine.
3. Unit tests pass.
4. Both the debug and release builds sync to the network.

**Comment by intelliot** [comment]
- Reverted https://github.com/XRPLF/rippled/pull/4505 and https://github.com/XRPLF/rippled/pull/4760

**Pull request merged**
