### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by wojake**
Added (Unstable) to Windows & changed "Server" -> "Node"

### Context of Change

1. The `rippled` software is unstable if ran in Windows, adding a notice besides the link is a safety measure.

2. It is more accurate that the `rippled` software is a *node* software as it interconnects with other nodes in the XRP Ledger.
In a client-server network, one node (the server) manages communication and resource access for the other nodes. Conversely, in a peer-to-peer network such as the XRPL, all nodes are the same since there is no central operator.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [X] Documentation Updates
- [ ] Release

### CODE REVIEW

**Review by cjcobb23 — COMMENTED** [review]
What's the motivation for changing "server" to "node"? I don't think there's anything wrong with "server", and that "server" is actually more descriptive than "node". There are a lot of non-server things that can be called a "node".

**Comment by wojake** [comment]
I see where you're coming from, most people think about a Client-Server model when the term "server" is used.
Using "node" would be more suitable in this situation as `rippled` would be apart of a peer-to-peer network.

**Comment by cjcobb23** [comment]
I see. How about we change line 3 to use "node", but keep line 8 using "server"?

**Comment by wojake** [comment]
> I see. How about we change line 3 to use "node", but keep line 8 using "server"?
Alright, done and thank you.

**Comment by cjcobb23** [comment]
@ximinez is rippled unstable if ran in windows?

**Comment by wojake** [comment]
Hey @bharathchari, just a follow up https://github.com/ripple/rippled/pull/3890#issuecomment-912929521, would you want to link xrpl.org's mailing list in this PR? If so, could you link it to me?

**Review by nbougalis — DISMISSED** [review]

**Review by intelliot — APPROVED** [review]

**Comment by manojsdoshi** [comment]
@wojake can you please rebase your PR to 1.9 it has merge conflicts thanks 🙏

**Comment by wojake** [comment]
This PR's changes have been made a long time ago, closing it.

**Pull request closed without merging**
