### PR TITLE
add result integer to transaction result codes

### PR DESCRIPTION
**Pull request by dangell7**
## High Level Overview of Change

Added the result code integer to the transaction results.

### Context of Change

This will help sidechains sync with the registry. Currently if a sidechain wanted to add their own amendment, they would need to bring in every tel code as a placeholder. This allows them to specify a specific result code while skipping other amendment result codes.

### Type of Change

- [x] Refactor (non-breaking change that only restructures code)

This would break everyone working on an amendment. You would get a clash but hopefully you can use the [registry](https://github.com/XRPLF/sFieldRegistry) to resolve and reserve your fields.

Its just a suggestion. No pressure.

### CODE REVIEW

**Comment by justinr1234** [comment]
I don’t have context to understand how this might affect existing or users.

Does this mean you’re expecting consumers to be able to do a greater than / less than compare?

**Comment by dangell7** [comment]
> I don’t have context to understand how this might affect existing or users.
> 
> Does this mean you’re expecting consumers to be able to do a greater than / less than compare?

See [here](https://github.com/XRPLF/rippled/pull/4292/files#diff-570760ccc79d416a7e98bf3e851c2e298ea5cf90f7207018e06aa6b46d09a013R124). See how on Xchain they needed to add the AMM error codes? This is because when generated without the absolute #, the error codes are generated in order. So for Xchain, they needed to add the AMM error codes in order to add their own error codes after. Or else there would have been a difference in error codes between the 2 builds. AMM error would have been 261 and the first Xchain error would have been 261 as well. 

I just thought it would be helpful if they were numbered.

**Comment by dangell7** [comment]
I'm going to move this draft and possibly close. After more thought, I don't know if it adds that much value. If you are writing an amendment or a sidechain then you need to be aware of the error codes anyways. Technically they are added when the amendment is merged so you have to keep up anyways. 

My bad lol

**Comment by justinr1234** [comment]
> I'm going to move this draft and possibly close. After more thought, I don't know if it adds that much value. If you are writing an amendment or a sidechain then you need to be aware of the error codes anyways. Technically they are added when the amendment is merged so you have to keep up anyways.
> 
> My bad lol

Heh wouldn’t say “your bad” but whatever you think is best! Thanks for helping my understand. 🙏🏻

**Comment by scottschurr** [comment]
Yeah, @dangell7, as you noted I don't know that this change helps the situation very much.

The two kinds of codes that need to be stable, `tes` and `tec`, already have explicit values.  It's important that they be stable because those values are stored in ledger history.  And, yeah, those need to be carefully managed as the code base changes.

For the other kinds of codes, `tel`, `tem` and the like, it is less critical that they stay stable.  I think it's okay for those values to accrete, as they have been, when code is merged to develop.

**Pull request closed without merging**
