### PR TITLE
Add a unit test for invalid memos

### PR DESCRIPTION
**Pull request by scottschurr**
## High Level Overview of Change

While reviewing a different pull request I noted that the code coverage of memos is not as good as it could be.  So I wrote a unit test to improve that coverage.

### Type of Change

- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)

### CODE REVIEW

**Review by ximinez — APPROVED** [review]
Nice clean set of tests.

**Review by gregtatcam — APPROVED** [review]
LGTM. 
One note - it didn't build for me with boost 1.80.0 (built with 1.75.0). On OSX I got this type of error:
src/ripple/beast/container/detail/aged_ordered_container.h:1435:53: error: no member named 'comp' in 'boost::intrusive::set_impl<boost::intrusive::bhtraits<beast::detail::aged_ordered_container<false, false, std::string, void, std::chrono::steady_clock, std::less<std::string>, std::allocator<std::string>>::element, boost::intrusive::rbtree_node_traits<void *, false>, boost::intrusive::normal_link, boost::intrusive::dft_tag, 3>, void, beast::detail::aged_ordered_container<false, false, std::string, void, std::chrono::steady_clock, std::less<std::string>, std::allocator<std::string>>::KeyValueCompare, unsigned long, true, void>'
    : m_config(other.m_config), m_cont(other.m_cont.comp())

**Review by intelliot — APPROVED** [review]
Successfully built on macOS

**Comment by intelliot** [comment]
CI failure is `0> #3 failed: NodeToShardRPC_test.cpp(47)` which is known to be flaky

**Pull request merged**
