### PR TITLE
Remove recipe for RocksDB and add recipe for Snappy

### PR DESCRIPTION
**Pull request by thejohnfreeman**
- Copies the recipe for Snappy from Conan Center, but removes three lines that explicitly link the standard library, which prevents builders from statically linking it.
- Removes the recipe for RocksDB now that an official recipe for version 6.27.3 is in Conan Center.

Developers will likely need to remove cached versions of both RocksDB and Snappy:

```
conan remove -f rocksdb
conan remove -f snappy
```

### CODE REVIEW

**Comment by thejohnfreeman** [comment]
CI is not expected to pass until we change the workflows to use Conan <2.0.

**Comment by intelliot** [comment]
note: the aforementioned PR to change the workflows to use Conan <2.0 is https://github.com/XRPLF/rippled/pull/4430

**Review by legleux — APPROVED** [review]
It would appear removing that libstdc++ line from the snappy recipe prevents the missing runtime dependency on Ubuntu and CentOS

**Comment by intelliot** [comment]
Merged via https://github.com/XRPLF/rippled/pull/4431

**Pull request closed without merging**
