### PR TITLE
Remove zaphod.alloy.ee from bootstrap

### PR DESCRIPTION
**Pull request by alloynetworks**
This PR has been made to remove the zaphod.alloy.ee hubs from the bootstrap after 5 years. It has been an honor to run these servers, but it is now time for another entity to step into this role.

The zaphod servers will be taken offline in a phased manner keeping all those who have peering arrangements informed. It is expected that this PR will be merged into the next release of `rippled` .

These would be the preferred attributes of a boostrap set of hubs:

1. Commitment to run the hubs for a minimum of 2 years
2. Highly available
3. Geographically dispersed
4. Secure and up to date
5. Committed to ensure that peering information is kept private

### CODE REVIEW

**Review by nbougalis — APPROVED** [review]
Effectively reverts f443439f1fc380602d2c09b5ae70551cb9effb06 from 2018... the end of an era.

Looks fine from a code perspective and can be merged whenever it's convenient.

**Review by ximinez — APPROVED** [review]
Thank you for your long-running contributions

**Comment by alloynetworks** [comment]
As 2.1.0 is just around the corner, this PR should be merged into the release after that - 2.2.0.

**Comment by jscottbranson** [comment]
The example config file should also be revised accordingly.

I'm grateful for the service this hub pool has provided over the last several years.

**Review by ximinez — CHANGES_REQUESTED** [review]
Good catch @jscottbranson! I'm adding this "request changes" review, so your comment doesn't get lost.

To reiterate, `zaphod.alloy.ee` needs to be removed from `cfg/rippled-example.cfg` and `cfg/rippled-reporting.cfg`.

**Comment by alloynetworks** [comment]
> Good catch @jscottbranson! I'm adding this "request changes" review, so your comment doesn't get lost.
> 
> To reiterate, `zaphod.alloy.ee` needs to be removed from `cfg/rippled-example.cfg` and `cfg/rippled-reporting.cfg`.

The lines have been removed from the example config files.

**Review by ximinez — APPROVED** [review]
I think that did it!
```
$ grep -r zaphod .

$
```

**Comment by ximinez** [comment]
@alloynetworks If this is ready to merge, please add the `Passed` label if you have permission, or leave a comment here indicating such.

**Comment by ximinez** [comment]
Suggested commit message:
```
Remove zaphod.alloy.ee hub from default server list: (#4903)

Remove the zaphod.alloy.ee hubs from the bootstrap and default configuration after 5 years. It has been an honor to run these servers, but it is now time for another entity to step into this role.

The zaphod servers will be taken offline in a phased manner keeping all those who have peering arrangements informed.

These would be the preferred attributes of a boostrap set of hubs:

    1. Commitment to run the hubs for a minimum of 2 years
    2. Highly available
    3. Geographically dispersed
    4. Secure and up to date
    5. Committed to ensure that peering information is kept private
```

**Pull request merged**
