### PR TITLE
Revert "Change enum values to be powers of two (fix #3417)"

### LINKED ISSUE #3417: Software does not distinguish between different Conditions (Version: 1.5)
I discovered some code that just doesn't smell right. I don't know the intended behavior, but I suspect the intent is different than what is actually happening.

The code that checks whether the condition that is required for a given RPC is met does not actually consider what condition is required. All of the conditions except `NO_CONDITION` are treated exactly the same. All of the following lines (in the same function) evaluate to the exact same value (false if `required_condition` is `NO_CONDITION` and true otherwise).
https://github.com/ripple/rippled/blob/3d86b49dae8173344b39deb75e53170a9b6c5284/src/ripple/rpc/impl/Handler.h#L80
https://github.com/ripple/rippled/blob/3d86b49dae8173344b39deb75e53170a9b6c5284/src/ripple/rpc/impl/Handler.h#L90
https://github.com/ripple/rippled/blob/3d86b49dae8173344b39deb75e53170a9b6c5284/src/ripple/rpc/impl/Handler.h#L91
https://github.com/ripple/rippled/blob/3d86b49dae8173344b39deb75e53170a9b6c5284/src/ripple/rpc/impl/Handler.h#L97
https://github.com/ripple/rippled/blob/3d86b49dae8173344b39deb75e53170a9b6c5284/src/ripple/rpc/impl/Handler.h#L117
The reason these lines all evaluate to the exact same value is because of the way these conditions are defined: all except `NO_CONDITION` have the least significant bit set to 1. So, when we bitwise and any two conditions together, the result is false if either are `NO_CONDITION` and true otherwise. I don't think this was the intended behavior of the code, since all of these lines could be replaced with `condition_required != NO_CONDITION`. Maybe someone who understands the intention of this piece of code can chime in here.

### PR DESCRIPTION
**Pull request by intelliot**
Consider the function `conditionMet`, specifically lines 121 and 122 and 146-147 of Handler.h: 

https://github.com/XRPLF/rippled/commit/1c2ae10dc057d5c7c76d0df2c5a92fc753e4769a#diff-41d8d23b15cb894b075204dcd88d7bf9ca223fa77f43e28bb22cf38b805cabfcL121-L122

https://github.com/XRPLF/rippled/commit/1c2ae10dc057d5c7c76d0df2c5a92fc753e4769a#diff-41d8d23b15cb894b075204dcd88d7bf9ca223fa77f43e28bb22cf38b805cabfcL146-L147

The change is broken: where it previously, it checked for a _specific_ condition (e.g. `NEEDS_CLOSED_LEDGER`) and only entered the `if` block if it was met, it now executes that code if _any_ condition is set.

A prime example of a RPC request that fails is the `tx` command, which has `NEEDS_NETWORK_CONNECTION` and will now not work unless the server has _both_ a current and a closed ledger.

The problem isn't the powers of two change. It's how the checks where restructured.

_Originally posted by @nbougalis in https://github.com/XRPLF/rippled/issues/4601#issuecomment-1615494006_
            

Reverts XRPLF/rippled#4239

### CODE REVIEW

**Comment by ckeshava** [comment]
Yes, reverting the commit will fix the problem. But I feel we also need to add additional unit tests, so that such blindspots are covered for the future.

**Review by ckeshava — APPROVED** [review]

**Review by HowardHinnant — CHANGES_REQUESTED** [review]
This revertible code isn't readable because it checks like a bit-mask even though it is not a bit-mask.

If the power-of-2 fix doesn't have the right behavior, it should be fixed with code that is more readable than this revert results in.  E.g. change the checks to use `==` instead of `&`.

That being said, @ximinez has an analysis that says the behavior between these two versions is the same, in which case I strongly prefer the power-of-2 version.

**Comment by ximinez** [comment]
Veto. Copying my comment from https://github.com/XRPLF/rippled/issues/4601#issuecomment-1622147627:

> A prime example of a RPC request that fails is the `tx` command, which has `NEEDS_NETWORK_CONNECTION` and will now not work unless the server has _both_ a current and a closed ledger.

I don't think there's a behavior change at all. I commented on the original PR to that effect: https://github.com/XRPLF/rippled/pull/4239#discussion_r1224782464

Here's more detail.

In the old code,

```
NO_CONDITION == 0
NEEDS_NETWORK_CONNECTION == 1 == 0b0001
NEEDS_CURRENT_LEDGER     == 3 == 0b0011
NEEDS_CLOSED_LEDGER      == 5 == 0b0101
```

Consider the condition on line 110:

```
condition_required & NEEDS_NETWORK_CONNECTION
```
which is equivalent to 
```
condition_required & 0b0001
```

`condition_required` can be any of those 4 values.

| `condition_required` | `condition_required & NEEDS_NETWORK_CONNECTION` | boolean result |
|-|-|-|
| `NO_CONDITION == 0` | `0` | `false` |
| `NEEDS_NETWORK_CONNECTION == 0b0001` | `0b0001` | `true` |
| `NEEDS_CURRENT_LEDGER == 0b0011` | `0b0001` | `true` |
| `NEEDS_CLOSED_LEDGER == 0b0101` | `0b0001` | `true` |

Basically, for any value except `NO_CONDITION` (0), the expression evaluates to `true`.

The new values are 0, 1, 2, and 4, respectively, but the result is the same. `condition_required != NO_CONDITION` in the new code is functionally equivalent to `condition_required & NEEDS_NETWORK_CONNECTION` in the old code.

It should be clear that the results are the same for the other values.

**Comment by intelliot** [comment]
Closing because @ckeshava and @ximinez agree that this should not be reverted; see https://github.com/XRPLF/rippled/issues/4601#issuecomment-1629688030

**Pull request closed without merging**
