### PR TITLE
Reduce console noise coming from unit tests:

### PR DESCRIPTION
**Pull request by scottschurr**
### Context of Change

A few unit tests have historically generated noise to the console caused by log writes.  This noise was not useful and made it harder to locate actual test failures.

By changing the log level of these tests from

- `severities::kError` to
- `severities::kDisabled`

it was possible to remove that noise coming from the logs.

Only those unit tests currently producing log noise were changed.  This is so, in the future, we can see if pre-existing unit tests start producing unexpected log noise.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by undertome** [comment]
I noticed about 135 lines fewer with your change, but I still picked up on some noise from `ValidatorSite` tests:

> ripple.app.ValidatorSite Fetch list - /redirect_forever/301 [https] v1 Exceeded max redirects
 -- Msg: max redirects
ripple.app.ValidatorSite Fetch list - /redirect_forever/307 [https] v1 Exceeded max redirects, /redirect_forever/308 [https] v1 Exceeded max redirects
 -- Msg: max redirects
 -- Msg: max redirects
ripple.app.ValidatorSite Fetch list - /validators [https] v1 , /redirect_forever/302 [https] v1 Exceeded max redirects
 -- Msg: max redirects
ripple.app.ValidatorSite Fetch list - /validators2 [https] v1 , /redirect_forever/302 [https] v1 Exceeded max redirects
 -- Msg: max redirects
ripple.app.ValidatorSite Fetch list - /redirect_to/ftp://invalid-url/302 [https] v1 Invalid redirect location
 -- Msg: Unsupported scheme: 'ftp'
ripple.app.ValidatorSite Fetch list - /redirect_to/file://invalid-url/302 [https] v1 Invalid redirect location
 -- Msg: file URI cannot contain a hostname
ripple.app.ValidatorSite Fetch list - /validators/bad [https] v1 Unable to parse JSON response
 -- Msg: bad json
ripple.app.ValidatorSite Fetch list - /validators2/bad [https] v1 Unable to parse JSON response
 -- Msg: bad json
ripple.app.ValidatorSite Fetch list - /bad-resource [https] v1 returned bad status
 -- Msg: bad result code
ripple.app.ValidatorSite Fetch list - /redirect_nolo/308 [https] v1 returned a redirect with no Location
 -- Msg: missing location
ripple.app.ValidatorSite Fetch list - /validators/missing [https] v1 Missing fields in JSON response
 -- Msg: missing fields
ripple.app.ValidatorSite Fetch list - /validators2/missing [https] v1 Missing fields in JSON response
 -- Msg: missing fields
ripple.app.ValidatorSite Fetch list - /sleep/13 [https] v1 took too long
 -- Msg: fetch error
ripple.app.ValidatorSite Fetch list - /validators [https] v2 Missing fields
 -- Msg: missing fields
ripple.app.ValidatorSite Fetch list - /validators2 [https] v0 Missing fields
 -- Msg: missing fields
ripple.app.ValidatorSite Fetch list - /validators [https] v4 Missing fields
 -- Msg: missing fields

Maybe it's not an issue, but I think we could get around this by changing the default log level in the `Env` constructor.

**Comment by scottschurr** [comment]
@undertome, yup, I saw those too.  Much of the noise from `ValidatorSite` results from the way that the names of the tests are generated, not from writes to the log.  I didn't feel like I had the expertise to monkey with the test naming for that particular test.  Yes, there's more noise that could be removed, but I feel like the commit as it stands is a good start.

**Review by ximinez — APPROVED** [review]
Looks good, and removes a lot of extra output.  For reference, here's what's left after I strip out all the test names. That's about 150 fewer lines of extra output from `develop`.
```
7>  -- Msg: max redirects
7>  -- Msg: max redirects
7>  -- Msg: max redirects
7>  -- Msg: max redirects
7>  -- Msg: max redirects
7>  -- Msg: Unsupported scheme: 'ftp'
7>  -- Msg: file URI cannot contain a hostname
7>  -- Msg: bad json
7>  -- Msg: bad json
7>  -- Msg: bad result code
7>  -- Msg: missing location
7>  -- Msg: missing fields
7>  -- Msg: missing fields
7>  -- Msg: fetch error
7>  -- Msg: missing fields
7>  -- Msg: missing fields
7>  -- Msg: missing fields
14> expected_probe_count_min: 10
expected_probe_count_max: 10
7>  -- Msg: max redirects
7>  -- Msg: max redirects
7>  -- Msg: max redirects
7>  -- Msg: max redirects
7>  -- Msg: max redirects
7>  -- Msg: Unsupported scheme: 'ftp'
7>  -- Msg: file URI cannot contain a hostname
7>  -- Msg: bad json
7>  -- Msg: bad json
7>  -- Msg: bad result code
7>  -- Msg: missing location
7>  -- Msg: missing fields
7>  -- Msg: missing fields
7>  -- Msg: fetch error
7>  -- Msg: missing fields
7>  -- Msg: missing fields
7>  -- Msg: missing fields
7>  -- Msg: bad json
7>  -- Msg: fetch error
7>  -- Msg: fetch error
7> Skipping rm dir: test_fetch1
11> 2E81FC6EC0DD943197E0C7E3FBE9AE307F2775F2F7485BB37307984C3C0F23409ED78915C6325F2EC67182FC916040556592DEDF7E8EEF67686570D4B2CC3053437CFC44ED39E3E58650C80C023EB01B7AA4E5E20BBF61A8A59FC2A711A38BEB11> ripple.app.PayStrand To Strand
12> Skipping rm dir: test_db1
12> Skipping rm dir: test_cfg6
12> Skipping rm dir: test_cfg7
12> Skipping rm dir: test_cfg8
Loading: "testSetup12\rippled.cfg"
12> Skipping rm dir: test_cfg9
12> Skipping rm dir: test_cfg9
Loading: "testSetup12\rippled.cfg"
Loading: "testSetup13\rippled.cfg"
Loading: "testSetup13\rippled.cfg"
12> Opened '' (ip=127.0.0.1:0, http)
12> server listening on port 60946
12> #1 accept:    127.0.0.1
12> #1 destroyed: 1 request
12> #2 accept:    127.0.0.1
12> #2 destroyed: 2 requests
10> [server] up on port: 51972
template_mismatch: Field 'Account' is required but missing.
template_mismatch: Field 'SignerWeight' is required but missing.
template_mismatch: Field 'Amount' found in disallowed location.
template_mismatch: Field 'Account' is required but missing.
15> Checking destination invariants...
```

**Comment by scottschurr** [comment]
@undertome, I've reduced the unit test noise further by removing some logging that I found I the unit tests.

**Review by undertome — APPROVED** [review]

**Review by ximinez — APPROVED** [review]
Still looks good

**Pull request closed without merging**
