### PR TITLE
Set version to 1.10.0-rc4

### PR DESCRIPTION
**Pull request by intelliot**
## High Level Overview of Change

Set version number for 1.10.0-rc4 release candidate.

### Context of Change

https://github.com/XRPLF/rippled/compare/e13676f...8687b5c

This release is rc3 with the addition of one code-impacting PR: https://github.com/XRPLF/rippled/pull/4442

### Type of Change

- [x] Release

### CODE REVIEW

**Review by kennyzlei — APPROVED** [review]

**Review by sgramkumar — APPROVED** [review]

**Comment by legleux** [comment]
https://github.com/XRPLF/rippled/pull/4445 required for packages to be pushed to `unstable` repos.

**Comment by intelliot** [comment]
#4445 is not required if this PR gets merged into `release` (in addition to `develop`). That is currently the plan, unless anyone objects.

**Comment by legleux** [comment]
> #4445 is not required if this PR gets merged into `release` (in addition to `develop`). That is currently the plan, unless anyone objects.

Closed #4445

**Comment by sublimator** [comment]
4444 !

**Pull request merged**
