### PR TITLE
Adapt to change in Conan recipe for NuDB

### PR DESCRIPTION
**Pull request by thejohnfreeman**

### CODE REVIEW

**Comment by sgramkumar** [comment]
QA build passed on ubuntu & MAC.

**Review by gregtatcam — COMMENTED** [review]
It didn't work. Tried on OSX. Deleted ~/.conan/data then ran `conan install ...` and then `cmake -D...`. `cmake` failed:

>     CMake Error at CMakeLists.txt:99 (target_link_libraries):
       The link interface of target "ripple_libs" contains:

        nudb::core

        but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

**Comment by scottschurr** [comment]
This branch is working for me on macOS.  Congrats!

MacOS: Ventura 13.4.1
conan: version 1.60.1
cmake: version 3.24.1

**Comment by scottschurr** [comment]
@gregtatcam, Yup.  Removed ~/.conan/data and my build directory before starting the process.

**Comment by gregtatcam** [comment]
> @gregtatcam, Yup. Removed ~/.conan/data and my build directory before starting the process.

Hm, ok. I must have missed something... Will give it another try.

**Review by gregtatcam — APPROVED** [review]
👍 LGTM

**Review by scottschurr — APPROVED** [review]
:+1:

**Pull request merged**
