### PR TITLE
Revise Build Instructions

### PR DESCRIPTION
**Pull request by oeggert**
Build instructions need to be updated in the repo in preparation for removal of [docs install pages](https://xrpl.org/install-rippled.html).

### CODE REVIEW

**Comment by intelliot** [comment]
(this is ready for someone to take a look)

**Comment by intelliot** [comment]
@oeggert how would you like to move this forward?

**Comment by oeggert** [comment]
Apologies; I pivoted to other doc priorities the last month. I'll update this according to the new build/install plan instructions and ping for review by end of week.

**Comment by oeggert** [comment]
Opened a new PR to address the revisions here: #4514

**Pull request closed without merging**
