### PR TITLE
[TRIVIAL] Add files generated by Conan to .gitignore

### PR DESCRIPTION
**Pull request by ximinez**
## High Level Overview of Change

No code changes. Conan generates several files in the rippled root folder (at least the way I've been building). This tells git to ignore those files.

### CODE REVIEW

**Review by ncirelli87 — COMMENTED** [review]
New Bin... Sweet

**Comment by thejohnfreeman** [comment]
I always feel like the only person in the world who prefers to keep project `.gitignore`s minimal and to put personal-choice build files into one's own user-level `.gitignore`.

**Review by thejohnfreeman — APPROVED** [review]

**Comment by thejohnfreeman** [comment]
I'll take this opportunity to once again recommend [Cupcake](https://github.com/thejohnfreeman/cupcake.py/blob/master/docs/tutorial.md) which will encapsulate all these build files into a hidden build directory by default, and relieve you from having to maintain personal build scripts, or search history for long command lines.

**Comment by ximinez** [comment]
> I always feel like the only person in the world who prefers to keep project `.gitignore`s minimal and to put personal-choice build files into one's own user-level `.gitignore`.

So two things I didn't realize
1. That these actually are artifacts of my build set up, and not something everyone is seeing. Should have asked if other folks were seeing the same files
2. That I can even have a user-level `.gitignore` file that expands on the project-level file. (Hint: `.git/info/exclude` is one way to do it.)

I'm going to close this PR and "clean up my own house" unless someone thinks this is valuable enough to re-open.

**Pull request closed without merging**
