### PR TITLE
Remove recipe for RocksDB and add recipe for Snappy

### PR DESCRIPTION
**Pull request by intelliot**
## High Level Overview of Change

- Copies the recipe for Snappy from Conan Center, but removes three lines that explicitly link the standard library, which prevents builders from statically linking it.
- Removes the recipe for RocksDB now that an official recipe for version 6.27.3 is in Conan Center.

Developers will likely need to remove cached versions of both RocksDB and Snappy:

```
conan remove -f rocksdb
conan remove -f snappy
```

### Context of Change

Without this change, we are unable to build packages for Ubuntu and CentOS. This will allow us to build and publish packages for the next release (1.10.0).

Removing that libstdc++ line from the snappy recipe prevents the missing runtime dependency on Ubuntu and CentOS.

This is a replacement for https://github.com/XRPLF/rippled/pull/4428 because I don't have permission to push the merge commit to @thejohnfreeman 's fork.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Release

### CODE REVIEW

**Review by seelabs — APPROVED** [review]
The changes look good, :+1:, but please don't commit with the "merge commits" in place. These commits should likely be squashed down to one commit (tho two would be OK too if you prefer)

**Comment by intelliot** [comment]
> please don't commit with the "merge commits" in place. These commits should likely be squashed down to one commit (tho two would be OK too if you prefer)

Agreed; it will be squashed to 1 commit. In fact, we currently have a branch protection rule enabled which rejects merge commits from being pushed to `develop` - i.e., it enforces linear history.

**Comment by intelliot** [comment]
For the record, it looks like the CI failure was:
```
1> ripple.tx.NFToken Mint flagOnlyXRP
0> #48 failed: Subscribe_test.cpp(993)
2> ripple.app.TrustAndBalance Payments With Paths and Fees
```

**Comment by intelliot** [comment]
For the record:
```
0> ripple.app.ValidatorSite Fetch list - /sleep/13 [http] v1 took too long
2> ripple.tx.NFTokenBurn Burn sequential
1> #53 failed: apply: Got temINVALID (The transaction is ill-formed.); Expected tesSUCCESS (The transaction was applied. Only final in a validated ledger.)
1> {
   "Account" : "rhxfiVBsvi5te9L2oevT9grLEU6zf9ezyv",
   "Fee" : "10",
   "NFTokenBuyOffer" : "761FDB3D8D4F4A48F0E29D945DED6D408FF2DC2ABF282BED83CD2C9EFF5D1FC9",
   "Sequence" : 12,
   "SigningPubKey" : "02DB81A69C2328C7ADD81F6DE8E08FEEF85C873AD2E2B76950072F2B06BA19D29B",
   "TransactionType" : "NFTokenAcceptOffer",
   "TxnSignature" : "30[450](https://github.com/XRPLF/rippled/actions/runs/4249615602/jobs/7400983272#step:19:451)221008EF1100A383FB94F86DEEF89C46F945D2437CD2FBCA0274811AB2CDCE60CC85202206C94A73B73E68E1F60F4A1D345BE2DF298FADA51BA766E9F47824279F5DADB54"
}

1> #55 failed: NFToken_test.cpp(1727)
1> #61 failed: apply: Got tecNO_LINE (No such line.); Expected tesSUCCESS (The transaction was applied. Only final in a validated ledger.)
1> {
   "Account" : "rhxfiVBsvi5te9L2oevT9grLEU6zf9ezyv",
   "Amount" : {
      "currency" : "CAD",
      "issuer" : "rExKpRKXNz25UAjbckCRtQsJFcSfjL9Er3",
      "value" : "100"
   },
   "Fee" : "10",
   "Flags" : 1,
   "NFTokenID" : "00081388AE123A8556F3CF91154711376AFB0F894F832B3D44B17C9E00000003",
   "Sequence" : 14,
   "SigningPubKey" : "02DB81A69C2328C7ADD81F6DE8E08FEEF85C873AD2E2B76950072F2B06BA19D29B",
   "TransactionType" : "NFTokenCreateOffer",
   "TxnSignature" : "3045022100F6C22878C595D2299CAFBE913B341E498DBF24A833FF5E8D65D0774302697BF202201FB6F77B26273647D1D6DB5D62AC371A529AE00DF5B92820B7B190E25BB7D2EC"
}

1> #62 failed: apply: Got tecOBJECT_NOT_FOUND (A requested object could not be located.); Expected tesSUCCESS (The transaction was applied. Only final in a validated ledger.)
1> {
   "Account" : "rP6P9ypfAmcJpw8SZHNwM4nvZHFXDraQas",
   "Fee" : "10",
   "NFTokenSellOffer" : "C05289930EB9DC97E3DB7F610A3FDB63CC40413270E9987E017E09C6907A008E",
   "Sequence" : 16,
   "SigningPubKey" : "0259EF099488D7633ADD34ABEC97C60D039B7F70BFDCE8605AD8A70E7DA3BEB3EE",
   "TransactionType" : "NFTokenAcceptOffer",
   "TxnSignature" : "3045022100AE08A3627FBD14464195AABC3796562137653556459F1B2D9301C87430838B6E022008D3D2D989089ADC04A958577CF14BCCE77E63E2A[458](https://github.com/XRPLF/rippled/actions/runs/4249615602/jobs/7400983272#step:19:459)2F5B2388C3A5C52686E6"
}

1> #63 failed: NFToken_test.cpp(1770)
1> ripple.tx.NFToken Mint flagTransferable
```

**Review by legleux — APPROVED** [review]
This fixes a dynamic link of libstdc++ that Snappy's conanfile sneaks in.

Not sure about the test failures.

**Review by thejohnfreeman — APPROVED** [review]

**Pull request merged**
