### PR TITLE
Proposed 2.0.0-rc6

### PR DESCRIPTION
**Pull request by intelliot**
## High Level Overview of Change

The only C++ code changes are reverts of https://github.com/XRPLF/rippled/pull/3839 and https://github.com/XRPLF/rippled/pull/4504.

### Context of Change

Ledgers with zero transactions were observed in Testnet, and the issue seems to be exacerbated by changes in `develop`. The two PRs reverted here were identified as potentially risky and are therefore being reverted until a more rigorous and realistic test harness is ready in 6-12 months.

### Type of Change

- [x] Release

### API Impact

- [x] Public API

Since this release candidate reverts #4505, it removes the "sync_mode" field which had been added to the transaction submission API.

## Test Plan

We expect to run this release candidate on Testnet for 2 weeks, with close observation to identify if any issues occur.

### CODE REVIEW

**Review by gregtatcam — APPROVED** [review]
Revert "Add ProtocolStart ..." PR #3839 looks fine to me.

**Comment by ckeshava** [comment]
all the unit tests pass on MacOS 👍

**Review by Bronek — APPROVED** [review]
I verified that change this looks exactly as I would expect it to look, compiles and passes test on Linux

**Comment by intelliot** [comment]
@HowardHinnant confirmed that tests are now passing.

**Pull request merged**
