### PR TITLE
Unit tests for AMM offer overflow fix

### PR DESCRIPTION
**Pull request by Bronek**
## High Level Overview of Change

Unit tests for https://github.com/XRPLF/rippled/pull/4968

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Performance (increase or change in throughput and/or latency)
- [x] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

### CODE REVIEW

**Review by gregtatcam — COMMENTED** [review]
Does it make sense to add expected offer balances? This way we can see the amounts going via AMM/LOB.

**Comment by ckeshava** [comment]
@gregtatcam I agree, please view it here: https://github.com/Bronek/rippled/pull/1

Qualitatively, the LOB offers are being used when one side of the AMM is being overwhelmed by `sendmax` parameter. This makes sense because LOB provides better quality offers whereas the AMM becomes capital-inefficient towards extremities.

However, I'm not familiar enough with the synthetic offer generation process to validate the actual numbers myself. Let me know if I can improve the validation further.

**Review by scottschurr — APPROVED** [review]
This test looks good to me as it is.  If you want to enhance it, I'm good with that too.

**Review by gregtatcam — APPROVED** [review]
LGTM

**Pull request merged**
