### PR TITLE
Add patched recipe for SOCI

### PR DESCRIPTION
**Pull request by thejohnfreeman**
See https://github.com/conan-io/conan-center-index/pull/17026#issuecomment-1522119607

Fixes build error:
```
Building CXX object src/core/CMakeFiles/soci_core_static.dir/values.cpp.o
In file included from /root/.conan/data/soci/4.0.3/_/_/build/e36423293cadd2b31097aec1d6bec7442146f2d7/src/src/backends/sqlite3/blob.cpp:9:
/root/.conan/data/soci/4.0.3/_/_/build/e36423293cadd2b31097aec1d6bec7442146f2d7/src/include/soci/sqlite3/soci-sqlite3.h:38:10: fatal error: sqlite3.h: No such file or directory
   38 | #include <sqlite3.h>
      |          ^~~~~~~~~~~
```

### CODE REVIEW

**Review by legleux — APPROVED** [review]
It worked!

**Review by sgramkumar — APPROVED** [review]
This fixes on both ubuntu (verified on 20.04) and Mac

**Review by intelliot — APPROVED** [review]

**Comment by Cogitri** [comment]
Please test https://github.com/conan-io/conan-center-index/pull/17245, if possible.

**Comment by legleux** [comment]
> Please test [conan-io/conan-center-index#17245](https://github.com/conan-io/conan-center-index/pull/17245), if possible.

@Cogitri I tested your PR and it worked.

**Comment by thejohnfreeman** [comment]
Looks good. Once it's in CCI, we can remove our custom recipe.

**Comment by Cogitri** [comment]
Grand, thanks

**Pull request merged**
