### PR TITLE
Enforce quorum when it is set via cmdline (for small and test networks)

### PR DESCRIPTION
**Pull request by RichardAH**
### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Comment by RichardAH** [comment]
closed in favour of https://github.com/XRPLF/rippled/pull/4489

**Comment by intelliot** [comment]
Sorry for the churn - thanks @RichardAH for being first to address this issue! If you don't mind, could you submit a code review on #4489?

**Comment by RichardAH** [comment]
> Sorry for the churn - thanks @RichardAH for being first to address this issue! If you don't mind, could you submit a code review on #4489?

Code authors shouldn’t be reviewers on their own code — even if it has been rewritten (uncredited) by someone else

**Comment by intelliot** [comment]
Would you like to be credited? Happy to add your name on it, of course.

**Pull request closed without merging**
